### PR TITLE
[v3] Move Practice Exercise example files to .meta directory

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The example implementation files for Practice Exercises should be located in the `.meta` directory. Besides being consistent with Concept Exercises, it also has the added benefit that no extra configuration is needed to prevent the example file from being downloaded to the student (as files in the `.meta` directory are never downloaded).

See [the spec](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-example-implementation).

This PR attempts to detect these example files and move them to the exercise's `.meta` directory.

Note that this change will likely break your CI, so feel free to either merge this and fix the build later, or push a fix to this PR.  

## Tracking

https://github.com/exercism/v3-launch/issues/18

### CODE REVIEW

**Comment by marnen** [comment]
This did break CI. Let me see about reconfiguring my .travis.yml file.

**Comment by marnen** [comment]
@ErikSchierboom Can you turn on "allow edits from maintainers" on this PR so I can fix the Travis configuration on this branch? Thanks!

**Comment by ErikSchierboom** [comment]
@marnen It was already enabled :)

**Comment by marnen** [comment]
@ErikSchierboom Ah, sorry for the confusion. It didn't seem like I could change anything, so I figured the box hadn't been checked. I'll get this working.

**Comment by marnen** [comment]
Hmm, I'm apparently missing something about the directory structure, and of course it takes forever to make changes and push everything to Travis. Maybe I can set up a Travis container locally. Anyway, I'll figure this out somehow!

**Comment by marnen** [comment]
Hmm. The test scripts run just fine in a local Docker container. I'm trying to figure out what's going on on Travis.

**Comment by marnen** [comment]
OK, the APL tests work. I think the problem now is Configlet, which is using old syntax.

**Review by marnen — APPROVED** [review]
Looks like this works now.

**Pull request merged**
