### PR TITLE
Rewrite ⎕FIO functions

### PR DESCRIPTION
**Pull request by marnen**
GNU APL's native file handling functions are of the form `⎕FIO[number]`, which isn't very readable, and 1.7 changed its semantics anyway (see #18). Fortunately, GNU APL also comes with a library that wraps the various `⎕FIO` functions with human-readable names, so we should use that.

### CODE REVIEW

**Comment by marnen** [comment]
@AtelesPaniscus @NewForester Does this branch work on GNU APL 1.7?

**Comment by AtelesPaniscus** [comment]
I guess not ... running the Hello World exercise gave two stack traces and a total of 128 lines of tantrum.

You will have to get travis working with GNL/APL 1.7.

**Comment by marnen** [comment]
@AtelesPaniscus Please provide the output you received.

**Comment by AtelesPaniscus** [comment]
Where ?  I will try to attach it here rather than paste it in from the clip board.

Dumb Windoze UI thinks it can deduce the file type from the file extension.  Try again.

It now days "Something went really wrong, and we can't process that file.  Try again".

Grr, grr ...

No, browse to upload failed as well.

[apl.txt](https://github.com/exercism/gnu-apl/files/1428430/apl.txt)

Ah,  There you go.  I hope you can access this.

**Comment by marnen** [comment]
Yup, I can see it. Pasting it in would actually have been a little easier to deal with, but I'll have a look and see what's going on. Thanks.

**Comment by marnen** [comment]
Looks like there's some issue with Unicode character handling. I wonder if I can reproduce, or if it's some Windows-specific build problem with the interpreter. Can you run other APL files in this environment? Also, which OS is it?

BTW, you shouldn't need the `-s` option to run the tests. Does omitting it change anything?

**Comment by marnen** [comment]
Wait, something else is going on too. I will try to fix this

**Comment by AtelesPaniscus** [comment]
OK.  What is your copy/paste limit ?  128 lines seems a lot to me.

How do you mean other APL files in this environment ?  I use the APL interpreter regularly but I don't go as far as using )COPY if that is what you mean.n  GNU/APL 1.7 is new - I installed it yesterday before reporting issue #18..

The -s suppresses the GNU/APL banner so there is less output I don't want to read.  It also suppresses the fancy coloured output that GNU 1.7 prefers.  When I invoke the interpreter from the command line I use --emacs otherwise output is black on black, which I can't read.

If you are referring Windows, the alternative proprietary operating system, then no.  The *nix world uses UTF-8 to represent Unicode while the Windows world uses UTF-16.  That should not matter to well behaved applications using stable run-time support.  The GNU/APL site says it should build under Cygwin but implies that if you dare you are one your own.

 I am using a rather old Debian 7.11 that receives security updates only.  I use Python 3 a lot, it is Unicode based and I have had no issues with it.  My GNU/APL was built (compiled from source) on the
machine that is running it.

It think it is premature to suspect the operating system:  it's a rabbit hole we don't want to go down.

I have seen GNU/APL 1.6 crash with stack traces so it comes to me with as no surprise that 1.7 has issues.

If it works for you, I will look into things further but I would start by cloning the Exercism repository rather than risk a mishap with _wget_.  Then I would try GNU/APL 1.6 again and only then try a Debian 8.

**Comment by marnen** [comment]
@AtelesPaniscus:

> OK. What is your copy/paste limit ? 128 lines seems a lot to me.

It isn't a lot, really. And you could always use `<details>` to make it collapsible. Or link to a Gist, but I tend to think that logs should usually be available in context.

The reason I think this may be due to a broken APL build has to do with the nature of one of the error messages:
`Bad UTF8 sequence: 0x87 at UTF8_string.cc`. Note the ".cc" there: this is an error thrown by something in C++, not by any APL code.

> The -s suppresses the GNU/APL banner so there is less output I don't want to read. It also suppresses the fancy coloured output that GNU 1.7 prefers. When I invoke the interpreter from the command line I use --emacs otherwise output is black on black, which I can't read.

Then you should read https://www.gnu.org/software/apl/apl.html#Section-3_002e3 regarding configuring colored output.

> I am using a rather old Debian 7.11 that receives security updates only.

OK. Your comments about "Dumb Windoze UI" made me assume that you were using Windows. Also, your log includes `)COPY FILE_IO.apl (file @GNU_APL_LIBS@/wslib5/FILE_IO.apl) failed: No such file or directory`, and the `@GNU_APL_LIBS@` bit certainly isn't *nix interpolation syntax...

How did you get GNU APL (not "GNU/APL"!) 1.7 to build on such an old Debian, BTW? It needs a fairly recent libstdc++6, which is why I haven't been using it on Ubuntu Trusty.

> If it works for you, I will look into things further but I would start by cloning the Exercism repository rather than risk a mishap with wget.

I'm not sure where wget would even come into this.

**Comment by AtelesPaniscus** [comment]
@marnen 

There is much that is new here to me.  I'm happy to learn and if that amuses you fine.  If it pisses you off I will go elsewhere.

> How did you get GNU APL (not "GNU/APL"!) 1.7 to build on such an old Debian, BTW? It needs a fairly recent libstdc++6, which is why I haven't been using it on Ubuntu Trusty.

```
    ./configure && make && sudo make install
```
I believe this to be the basic command for any automake based build.  I used it first for GNU APL1.6 after reading the INSTALL notes.  I think the build runs a number of _.tc_ tests cases.  Since there was no final message to the contrary I natively assumed the build was successful.  Next time I do this I will be more vigilant.

> I'm not sure where wget would even come into this.

```bash
wget -O test.apl https://github.com/exercism/gnu-apl/blob/rewrite-fio/test.apl?raw=true
   # or
wget https://raw.githubusercontent.com/exercism/gnu-apl/rewrite-fio/test.apl
```
How would you grab an up-to-date copy of a single file from GitHub ?

> The reason I think this may be due to a broken APL build has to do with the nature of one of the error messages: Bad UTF8 sequence: 0x87 at UTF8_string.cc.

Yeah, I get that from time to time but only when trying to correct my own bad typing.  I would not expect it to occur when reading a file off disk.  GitHub is not good at giving md5sum or other means to confirm downloads are good but I have now compared the _test.apl_ I downloaded with _wgetc_ with the copy inside the zip available from the GitHub UI.  Same checksum.

> It isn't a lot, really. And you could always use <details> to make it collapsible. Or link to a Gist, but I tend to think that logs should usually be available in context.

Things have moved on since the days when folk pasted logs that meant I could not see the wood for the trees and I had to ask them to use attachments instead.

I think I see what you mean about `<describe>`.  I like that.  I have never used GIST but if you had suggested it, I would have done my best to find out how to.  Until such an occasion arises, I have little incentive to post logs to myself.

**Comment by marnen** [comment]
@AtelesPaniscus:

> There is much that is new here to me. 

And to me. I'm pretty much a beginner in APL, and am creating this track basically because it didn't already exist and no one else was going to do it. :)

> I'm happy to learn and if that amuses you fine. If it pisses you off I will go elsewhere.

I really appreciate having someone else playing with and finding bugs; please do continue. Just remember that this track isn't ready for release yet, so don't expect everything to work perfectly.

Since you brought it up, though...I wouldn't have used the phrase "pissed off", but it does sometimes seem that your suggestions could benefit from less antagonistic phrasing and a better understanding of the whole picture. (I mean this constructively; these are communication issues that I often run into myself, so I do sympathize.)

> How did you get GNU APL (not "GNU/APL"!) 1.7 to build on such an old Debian, BTW? It needs a fairly recent libstdc++6, which is why I haven't been using it on Ubuntu Trusty.
> > `./configure && make && sudo make install`

Ah, OK; I'm surprised that that worked. I've been building from the .deb packages, for which 1.7 requires the newer libstdc++6.

At any rate, it *does* appear that 1.7 is buggy and won't work with Exercism. See https://github.com/exercism/gnu-apl/pull/21#issuecomment-341204906 for more on that and a suggestion on what build to use.

**Comment by marnen** [comment]
And with this merge, all should now work on APL 1.7@SVN945.

**Comment by AtelesPaniscus** [comment]
@marnen 

Yes, an introduction is in order.  British English my mother tongue and my English is no longer even contemporary British English.  I am aware that many misunderstand what I write to some degree, most more than they realise, and this goes for British people too.  My apologies if my forthrightness comes over as antagonistic.

I learnt APL 40 years ago but have not used it in decades.   I have picked up again as part of a private study of functional programming.  It might have been the original FPL but functional programming has come a long way since.

I loved APL as a young man much as I loved mathematics as a child.  It is great for crunching numbers but very awkward for anything else.  It has evolved but not that much.  I would never attempt 'tooling' in APL as you have done (and I would learn a new language like Go if I had to).

What is new to me is the Exercism project and its way of doing things and GitHub and its way of doing things.  My experience with Open Source is that a project is the property of the one ego and woe betide anyone whose behaviour could be taken as suggesting it should be shared.  I will not mention tooling again.

I must look up _travis_ on WIkipedia to make sure my guess as to what it is is not totally wide of the mark.  I should read the GitHub documentation on _gist_ too.

----

I have built deb packages in the past (but not for the Debian, or any other Open Source, project, more's the pity).  Package dependencies are about a consistent set of packages.  If someone packages a new application release, like APL 1.7, it will be for a particular release of the OS and so the dependencies will list that OS release's version of libstdc++6 etc. etc.  Some people do 'backport' to older versions of the OS and sometimes that is just a case of rebuilding the package from source and adjusting the dependencies.

**Pull request merged**
